# Created using wingetcreate

PackageIdentifier: Ultimaker.Cura
PackageVersion: 4.10.0
PackageLocale: en-US
Publisher: Ultimaker
PackageName: Cura
License: GNU Lesser General Public License v3.0
ShortDescription: Trusted by millions of users, Ultimaker Cura is the world’s most popular 3D printing software. Prepare prints with a few clicks, integrate with CAD software for an easier workflow, or dive into custom settings for in-depth control.
ManifestType: defaultLocale
ManifestVersion: 1.0.0
